apiVersion: v1
kind: Namespace
metadata:
  name: gihernandez

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: gihernandez
data:
  USERNAME: "gihernandez"

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: gihernandez
type: Opaque
data:
  API_KEY: "Z2loZXJuYW5kZXp0YXJlYWZpbmFs"   # "gihernandeztareafinal" en base64

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test
  namespace: gihernandez
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
        - name: backend-test
          image: docker.io/gihernandezl/backend-test:latest  # luego Jenkins actualiza con build number
          ports:
            - containerPort: 3000
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USERNAME

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: API_KEY

---

apiVersion: v1
kind: Service
metadata:
  name: backend-test-service
  namespace: gihernandez
spec:
  selector:
    app: backend-test
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
